### ISSUE TITLE
Short links return 404

### ISSUE THREAD

**Issue by barnumbirr** [alferz/worldcoin-abe#1]
All the short links return 404 errors:

https://www.wdcexplorer.com/block/b55e8e2dc1f506c21bb9b41572fbcb729e0732b31e1920e4b99baec58435b781 works fine but it's short link (https://www.wdcexplorer.com/b/12ZKNBmfRE) doesn't.
Same for address short links: https://www.wdcexplorer.com/address/WfupYv4fqeYDAXAtN7VEaFHbVfjnBStMvD works but this doesn't: https://www.wdcexplorer.com/b/12ZKNBmfRE.

Cheers.

**Comment by alferz** [comment]
Thanks mrsmn, while I was simplifying the original codebase I missed that the handle_a, handle_b, and handle_t functions were facilitating the decoding function for the short links. I added those back in and deployed to PROD so just let me know if you see anything still outstanding.

**Comment by barnumbirr** [comment]
Hi there @alferz,

thank you for fixing this, works perfectly now :smile:

Cheers.
